[package]
name = "trivial-graph-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trivial-graph = { path = "trivial-graph", version = "0.1" }